cars/urls.py
from django.urls import path
from cars.views import CarBulkUpdate, CarListView, CarCreateView, CarUpdateView, CarDeleteView, CarDetailView, index
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cars_urls'

urlpatterns = [
    path('', index, name="index"),
    path('cars/detail/<int:pk>/', CarDetailView.as_view(), name='detail'),
    path('cars/create/', CarCreateView.as_view(), name='create'),
    path('cars/', CarListView.as_view(), name='list'),
    path('cars/update/<int:pk>/', CarUpdateView.as_view(), name='update'),
    path('cars/delete/<int:pk>', CarDeleteView.as_view(), name="delete" ),
    path('bulk_update/', CarBulkUpdate.as_view(), name='car_bulk_update'),
] +  static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) #pra add imagens

setup/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls', namespace='cars_urls')),
    path('', include('users.urls', namespace='users_urls')),
    path('', include('rents.urls', namespace='rents_urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

cars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    model = models.CharField(max_length=100)
    manufacter = models.CharField(max_length=100)
    color = models.CharField(max_length=100, null=True, blank=True)
    year = models.CharField(max_length=4)
    motor = models.CharField(max_length=20, null=True, blank=True)
    fuel_type = models.CharField(max_length=100, null=True, blank=True)
    license_plate = models.CharField(max_length=8, null=True, blank=True, unique=True)
    photo = models.FileField(upload_to='carros', blank=True)

    def __str__(self):
        return self.model

cars/forms.py
from .models import Car
from django.forms import ModelForm

class carForm(ModelForm):
    class Meta:
        model = Car
        fields = '__all__'

        labels = {
            'model': 'Modelo',
            'manufacter': 'Marca',
            'color': 'Cor do Veículo',
            'year': 'Ano',
            'motor': 'Motor',
            'fuel_type': 'Tipo de Combustível',
            'license_plate': 'Placa',
        }

class carBulkUpdate(ModelForm):
    class Meta:
        model = Car
        fields = ['motor',]

cars/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from cars.models import Car
from .forms import carBulkUpdate, carForm

from django.views.generic import ListView, FormView, UpdateView, DetailView, DeleteView

# Create your views here.
def index(request):
    produtos = Car.objects.all()
    return render(request, "index.html", context={'produtos': produtos})

class CarListView(ListView):
    model = Car
    queryset = Car.objects.all()
    template_name = "cars/car_list.html"
    paginate_by = 4
    
class CarCreateView(FormView):
    template_name = 'cars/car_form.html'
    form_class = carForm
    success_url = reverse_lazy('cars_urls:index')

    def form_valid(self, form):
        form.save()  # Salva o objeto Car no banco de dados
        return super().form_valid(form)

class CarUpdateView(UpdateView):
    model = Car
    form_class = carForm
    template_name = 'cars/car_form.html'
    success_url = reverse_lazy('cars_urls:list')

class CarDetailView(DetailView):
    model = Car
    queryset = Car.objects.all()

class CarDeleteView(DeleteView):
    model = Car
    slug_field = 'slug'  # campo de slug no modelo Car
    slug_url_kwarg = 'slug'  # nome do parâmetro na URL
    success_url = reverse_lazy('cars_urls:index')
    template_name = 'cars/car_confirm_delete.html'

class CarBulkUpdate(FormView):
    template_name = 'cars/car_bulk_update.html'
    form_class = carBulkUpdate
    success_url = reverse_lazy('cars_urls:index')

    def form_valid(self, form):
        motor = form.cleaned_data['motor']
        Car.objects.update(motor=motor)
        return super().form_valid(form)

cars/templates/cars/car_bulk_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block titulo %}Bulk Update de Carros{% endblock %}

{% block centro %}
<div class="container p-4 col-xs-6 col-sm-4 vh-100">


  <h1 class="text-center pt-4">Bulk Update de Carros</h1>
  <p class="lead text-center pt-4"> Preencha o campo abaixo:</p>

  <form action="." enctype='multipart/form-data' method="POST" class="p-4">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="text-center">
      <button type="submit" class="btn btn-primary mb-4 mt-4">Atualizar Motores</button>
    </div>

  </form>

</div>
{% endblock %}

cars/templates/cars/car_confirm_delete.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}


{% block centro %}
<div class="container-fluid d-flex align-items-center justify-content-center vh-100">

  <div class="main">
    <!-- Create a Form -->
    <form method="POST" class="p-4">
        <!-- Security token by Django -->
        {% csrf_token %}
        Tem certeza que quer deletar essa locação?
        <input type="submit" class="btn btn-danger" value="Deletar"/>
        <button class="btn btn-secondary">
          <a href="{% url 'cars_urls:index' %}" class="text-white"> 
            Cancelar
          </a>
        </button>
    </form>
  </div>

</div>
{% endblock %}

cars/templates/cars/car_detail.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
Index
{% endblock %}

{% block centro %}

{% if request.user.is_authenticated %}

<div class="d-flex justify-content-center mt-4">

  <table class="table table-striped table-light">
    <thead>
      <tr>
        <th scope="col">Foto:</th>
        <th scope="col">Modelo:</th>
        <th scope="col">Marca:</th>
        <th scope="col">Cor:</th>
        <th scope="col">Ano:</th>
        <th scope="col">Placa:</th>
        <th scope="col">Motor:</th>
        <th scope="col">Combustível:</th>
        <th scope="cop">Editar:</th>
        <th scope="cop">Deletar:</th>
      </tr>
    </thead>
    <tbody>
       <tr>
        <td><img src="/media/{{object.photo}}" height="200px" width="250px"></td>
        <td>{{ object.model }}</td>
        <td>{{ object.manufacter }}</td>
        <td>{{ object.color }}</td>
        <td>{{ object.year }}</td>
        <td>{{ object.license_plate }}</td>
        <td>{{ object.motor }}</td>
        <td>{{ object.fuel_type }}</td>
        <td>
          <a href="{% url 'cars_urls:update' object.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
              <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
            </svg>
          </a>
        </td>
        <td>
          <a href="{% url 'cars_urls:delete' object.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
              <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
            </svg>  
          </a>
        </td>
      </tr>
    </tbody>
  </table>

</div>

<div class="d-flex justify-content-center">

  <a href="{% url 'rents_urls:create' %}"><button class="btn btn-primary mb-4" type="submit"> Alugar
      Veículo</button></a>

</div>
{% else %}
<div class="d-flex justify-content-center mt-4">

  <table class="table table-striped table-light">
    <thead>
      <tr>
        <th scope="col">Foto:</th>
        <th scope="col">Modelo:</th>
        <th scope="col">Marca:</th>
        <th scope="col">Cor:</th>
        <th scope="col">Ano:</th>
        <th scope="col">Placa:</th>
        <th scope="col">Motor:</th>
        <th scope="col">Combustível:</th>
        <th scope="cop">Deletar:</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><img src="/media/{{object.foto}}" height="200px" width="250px"></td>
        <td>{{ object.model }}</td>
        <td>{{ object.manufacter }}</td>
        <td>{{ object.color }}</td>
        <td>{{ object.year }}</td>
        <td>{{ object.license_plate }}</td>
        <td>{{ object.motor }}</td>
        <td>{{ object.fuel_type }}</td>
        <td>
          <a href="{% url 'cars_urls:delete' object.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
              <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
            </svg>  
          </a>
        </td>
      </tr>
    </tbody>
  </table>

</div>

{% endif %}


{% endblock %}

cars/templates/cars/car_form.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Cadastrar Carro
{% endblock %}

{% block centro %}
<div class="container p-4 col-xs-6 col-sm-4">

    <h1 class="text-center pt-4">Cadastro de Carros</h1>
    <p class="lead text-center pt-4"> Preencha os campos abaixo:</p>

    <form action="." enctype='multipart/form-data' method="POST" class="p-4">

        {% csrf_token %}

        {{ form|crispy }}
        <div class="text-center">
            <button type="submit" class="btn btn-primary mb-4 mt-4">Cadastrar</button>
        </div>
    </form>

</div>
{% endblock %}

cars/templates/cars/car_list.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
Listar Carros{% endblock %}

{% block centro %}
<div class="container-fluid d-flex align-items-center justify-content-center">
    <div class="text-center">

    <h2 class="text-center mb-4"> Carros Cadastrados</h2>
        
    <div class="row">
    
        {% for car in object_list %}

        <div class="col mb-5">

            <div class="card" style="width: 18rem;">
                <!-- Product image-->
                <img class="card-img-top" src="/media/{{car.photo}}" height="200px" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{ car.model }}</h5>
                        <!-- Product price-->
                        {{ car.year }}
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-primary mt-auto"
                            href="{% url 'cars_urls:detail' car.id %}">Detalhes</a></div>
            </div>

        </div>

    </div>

    {% endfor %}
    </div>

    {% include 'partials/pagination.html' %}
      
</div>

</div>
{% endblock %}