alugueis/urls.py
from django.urls import path
from .views import *

app_name = 'alugueis_urls'

urlpatterns = [
    path('cadastrarLocacao/', cadastrarLocacao, name='cadastrarAluguel'),
    path('listarLocacoes/', listarLocacoes, name='listarLocacoes'),
    path('delete/locacao/<int:id>', deletarLocacao, name="deletarLocacao" ),
]

carros/urls.py
from django.urls import path
from carros.views import paginaInicial, detalheCarro, cadastrarCarro, deletarCarro
from django.conf import settings
from django.conf.urls.static import static

app_name = 'carros_urls'

urlpatterns = [
    path('', paginaInicial, name="paginaInicial"),
    path('detalheCarro/<int:id_produto>/', detalheCarro, name="detalheCarro"), 
    path('cadastrarCarros/', cadastrarCarro, name='cadastrarCarro'),
    path('delete/carro/<int:id>', deletarCarro, name="deletarCarro" ),
] +  static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) #pra add imagens

cars/urls.py
from django.urls import path
from cars.views import CarBulkUpdate, CarListView, CarCreateView, CarUpdateView, CarDeleteView, CarDetailView, index
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cars_urls'

urlpatterns = [
    path('', index, name="index"),
    path('cars/detail/<int:pk>/', CarDetailView.as_view(), name='detail'),
    path('cars/create/', CarCreateView.as_view(), name='create'),
    path('cars/', CarListView.as_view(), name='list'),
    path('cars/update/<int:pk>/', CarUpdateView.as_view(), name='update'),
    path('cars/delete/<int:pk>', CarDeleteView.as_view(), name="delete" ),
    path('bulk_update/', CarBulkUpdate.as_view(), name='car_bulk_update'),
] +  static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) #pra add imagens

rents/urls.py
from django.urls import path
from .views import *

app_name = 'rents_urls'

urlpatterns = [
    path('rents', RentListView.as_view(), name='list'),
    path('rents/detail/<int:pk>/', RentDetailView.as_view(), name='detail'),
    path('rents/create/', RentCreateView.as_view(), name='create'),
    path('rents/update/<int:pk>/', RentUpdateView.as_view(), name='update'),
    path('rents/delete/<int:pk>', RentDeleteView.as_view(), name="delete" ),
]

setup/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls', namespace='cars_urls')),
    path('', include('users.urls', namespace='users_urls')),
    path('', include('rents.urls', namespace='rents_urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

rents/models.py
from django.db import models
from cars.models import Car
from users.models import Client

# Create your models here.
class Rent(models.Model):
    pickup_date = models.DateField()
    delivery_date = models.DateField()
    value = models.FloatField()
    client =  models.OneToOneField(Client, on_delete=models.CASCADE)
    car =  models.OneToOneField(Car, on_delete=models.CASCADE)

    def __str__(self):
        return self.car.model

rents/forms.py
from .models import Rent
from django import forms
from django.forms import TextInput

class rentForm(forms.ModelForm):

    class Meta:
        model = Rent
        fields = '__all__'

        labels = {
            'pickup_date': 'Data de Retirada',
            'value': 'Valor',
            'delivery_date': 'Data de Entrega',
            'client': 'Cliente',
            'car': 'Carro',
        }

        widgets = {
            'pickup_date': forms.DateInput(
                    format = '%d/%m/%Y', 
                    attrs={
                        'type':'date',
                        'class':'form-control'
                    }
                ),
            'delivery_date': forms.DateInput(
                    format = '%d/%m/%Y', 
                    attrs={
                        'type':'date',
                        'class':'form-control'
                    }
                ),

        }

rents/views.py
from django.views.generic import ListView, FormView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy
from rents.models import Rent
from .forms import rentForm

# Create your views here.
class RentListView(ListView):
    model = Rent
    queryset = Rent.objects.all()
    template_name = "rents/rent_list.html"
    paginate_by = 4

class RentCreateView(FormView):
    template_name = 'rents/rent_form.html'
    form_class = rentForm
    success_url = reverse_lazy('rents_urls:list')

    def form_valid(self, form):
        form.save()  # Salva o objeto Rent no banco de dados
        return super().form_valid(form)

class RentUpdateView(UpdateView):
    model = Rent
    form_class = rentForm
    template_name = 'rents/rent_form.html'
    success_url = reverse_lazy('rents_urls:list')

class RentDetailView(DetailView):
    model = Rent
    queryset = Rent.objects.all()

class RentDeleteView(DeleteView):
    model = Rent
    slug_field = 'slug'  # campo de slug no modelo Rent
    slug_url_kwarg = 'slug'  # nome do parâmetro na URL
    success_url = reverse_lazy('cars_urls:index')
    template_name = 'rents/rent_confirm_delete.html'

rents/templates/aluguel/formAlugar.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Cadastro de Locação
{% endblock %}

{% block centro %}
<div class="container p-4 col-xs-6 col-sm-4">

    <h1 class="text-center pt-4">Cadastro de Locação</h1>
    <p  class="lead text-center pt-4"> Preencha os campos abaixo:</p>

    <form action="." method="POST" class="p-4"> 

        {% csrf_token %}

        {{ primeiroForm|crispy }}

        <button type="submit" class="btn btn-primary mb-4 mt-4">Alugar</button>
    </form>

</div>
{% endblock %}

rents/templates/aluguel/formDelete.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}


{% block centro %}
<div class="container-fluid">

  <div class="main">
    <!-- Create a Form -->
    <form method="POST" class="p-4">
        <!-- Security token by Django -->
        {% csrf_token %}
        Tem certeza que quer deletar essa locação?
        <input type="submit" class="btn btn-danger" value="Deletar"/>
        <button class="btn btn-secondary">
          <a href="{% url 'carros_urls:paginaInicial' %}" class="text-white"> 
            Cancelar
          </a>
        </button>
    </form>
  </div>

</div>
{% endblock %}

rents/templates/aluguel/listarLocacoes.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
Listar Locações
{% endblock %}

{% block centro %}
<div class="container-fluid p-4 text-center">

    <h1 class="text-align-center pb-4">Locações Cadastrados</h1>

    <div class="row">

      {% for locacao in locacoes %}

        <div class="col mb-5" >

          <div class="card" style="width: 18rem;">
            <div class="card-header">
              Cliente: {{ locacao.cliente.nome }}
              <a href="{% url 'alugueis_urls:deletarLocacao' locacao.id %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>  
              </a>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Carro: {{ locacao.carro.modelo }}, {{ locacao.carro.ano }}, {{ locacao.carro.cor }}, {{ locacao.carro.placa }}</li>
              <li class="list-group-item"> Retirada: {{ locacao.data_retirada }} </li>
              <li class="list-group-item">Entrega: {{ locacao.data_entrega }}</li>
              <li class="list-group-item">Valor da locação: {{ locacao.valor }}</li>
            </ul>
          </div>
        
        </div>

      {% endfor %}
    
    </div>
    
</div>
{% endblock %}