carros/urls.py
from django.urls import path
from carros.views import paginaInicial, detalheCarro, cadastrarCarro, deletarCarro
from django.conf import settings
from django.conf.urls.static import static

app_name = 'carros_urls'

urlpatterns = [
    path('', paginaInicial, name="paginaInicial"),
    path('detalheCarro/<int:id_produto>/', detalheCarro, name="detalheCarro"), 
    path('cadastrarCarros/', cadastrarCarro, name='cadastrarCarro'),
    path('delete/carro/<int:id>', deletarCarro, name="deletarCarro" ),
] +  static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) #pra add imagens

cars/urls.py
from django.urls import path
from cars.views import CarBulkUpdate, CarListView, CarCreateView, CarUpdateView, CarDeleteView, CarDetailView, index
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cars_urls'

urlpatterns = [
    path('', index, name="index"),
    path('cars/detail/<int:pk>/', CarDetailView.as_view(), name='detail'),
    path('cars/create/', CarCreateView.as_view(), name='create'),
    path('cars/', CarListView.as_view(), name='list'),
    path('cars/update/<int:pk>/', CarUpdateView.as_view(), name='update'),
    path('cars/delete/<int:pk>', CarDeleteView.as_view(), name="delete" ),
    path('bulk_update/', CarBulkUpdate.as_view(), name='car_bulk_update'),
] +  static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) #pra add imagens

setup/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls', namespace='cars_urls')),
    path('', include('users.urls', namespace='users_urls')),
    path('', include('rents.urls', namespace='rents_urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

users/urls.py
from django.urls import path
from .views import *

app_name = 'users_urls'

urlpatterns = [
    path('conta/login/', LoginView.as_view(), name="login"),
    path('conta/logout/', LogoutView.as_view(), name='logout'),
    path("conta/registrar/", RegisterView.as_view(), name="registrar"),
    path('clients/', ClientListView.as_view(), name='list'),
    path('clients/detail/<int:pk>/', ClientDetailView.as_view(), name='detail'),
    path('clients/create/', ClientCreateView.as_view(), name='create'),
    path('clients/update/<int:pk>/', ClientUpdateView.as_view(), name='update'),
    path('clients/delete/<int:pk>', ClientDeleteView.as_view(), name="delete" ),
]

usuarios/urls.py
from django.urls import path
from .views import *

app_name = 'usuarios_urls'

urlpatterns = [
    path('conta/login/', my_login, name="login"),
    path('conta/logout/', logout_request, name='logout'),
    path("conta/registrar/", register, name="registrar"),
    path('cadastrarClientes/', cadastrarCliente, name='cadastrarCliente'),
    path('clientes/listarClientes/', listarClientes, name='listarClientes'),
    path('delete/cliente/<int:id>', deletarCliente, name="deletarCliente" ),
]

users/models.py
from django.db import models

# Create your models here.
class Client(models.Model):
    name = models.CharField(max_length=200)
    cpf = models.CharField(max_length=15, unique=True)
    address = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    phone_number = models.CharField(max_length=20)
    cnh = models.CharField(max_length=11, null=True, blank=True, unique=True)

    def __str__(self):
        return self.name

users/forms.py
from django import forms
from django.forms.models import ModelForm
from .models import Client
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class clientForm(ModelForm):

    class Meta:
        model = Client
        fields = '__all__'
	
        labels = {
            'name': 'Nome',
            'cpf': 'CPF',
            'cnh': 'CNH',
            'email': 'E-mail',
            'phone_number': 'Telefone',
            'address': 'Endereço',
        }

users/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.urls import reverse_lazy
from .forms import NewUserForm, clientForm
from .models import Client
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm 
from django.views import View
from django.views.generic import ListView, FormView, UpdateView, DetailView, DeleteView

# Create your views here.

#user
class RegisterView(View):
    def get(self, request):
        form = NewUserForm()
        return render(request=request, template_name="registrations/register_form.html", context={"register_form": form})

    def post(self, request):
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("cars_urls:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
        return render(request=request, template_name="registrations/register_form.html", context={"register_form": form})


class LoginView(View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request=request, template_name="login/login.html", context={"form": form})

    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("cars_urls:index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
        return render(request=request, template_name="login/login.html", context={"form": form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.info(request, "Você realizou logout com sucesso!")
        return redirect("cars_urls:index")


class RegisterRequestView(View):
    def get(self, request):
        form = NewUserForm()
        return render(request=request, template_name="registrations/register_form.html", context={"register_form": form})

    def post(self, request):
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("cars_urls:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
        return render(request=request, template_name="registrations/register_form.html", context={"register_form": form})
    
#cliente

class ClientListView(ListView):
    model = Client
    queryset = Client.objects.all()
    template_name = "clients/client_list.html"
    paginate_by = 4
    
class ClientCreateView(FormView):
    template_name = 'clients/client_form.html'
    form_class = clientForm
    success_url = reverse_lazy('cars_urls:index')

    def form_valid(self, form):
        form.save() 
        return super().form_valid(form)

class ClientUpdateView(UpdateView):
    model = Client
    form_class = clientForm
    template_name = 'clients/client_form.html'
    success_url = reverse_lazy('users_urls:list')

class ClientDetailView(DetailView):
    model = Client
    queryset = Client.objects.all()

class ClientDeleteView(DeleteView):
    model = Client
    slug_field = 'slug'  
    slug_url_kwarg = 'slug' 
    success_url = reverse_lazy('cars_urls:index')
    template_name = 'clients/client_confirm_delete.html'
    
	# class RegisterView(View):
#     def get(self, request):
#         form = NewUserForm()
#         return render(request, "cadastros/register_form.html", {"register_form": form})

#     def post(self, request):
#         form = NewUserForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request, user)
#             messages.success(request, "Registration successful.")
#             return redirect("cars_urls:index")
#         else:
#             messages.error(request, "Unsuccessful registration. Invalid information.")
        
#         return render(request, "cadastros/register_form.html", {"register_form": form})

# def register(request):
# 	if request.method == "POST":
# 		form = NewUserForm(request.POST)
# 		if form.is_valid():
# 			user = form.save()
# 			login(request, user)
# 			messages.success(request, "Registration successful." )
# 			return redirect("cars_urls:index")
# 		messages.error(request, "Unsuccessful registration. Invalid information.")
	
# 	form = NewUserForm()	
# 	return render (request=request, template_name="cadastros/register_form.html", context={"register_form":form})


# def my_login(request):
# 	if request.method == "POST":
# 		form = AuthenticationForm(request, data=request.POST)
# 		if form.is_valid():
# 			username = form.cleaned_data.get('username')
# 			password = form.cleaned_data.get('password')
# 			user = authenticate(username=username, password=password)

# 			if user is not None:
# 				login(request, user) 
# 				return redirect("cars_urls:index") 
# 			else:
# 				messages.error(request,"Invalid username or password.")
# 		else:
# 			messages.error(request,"Invalid username or password.")
# 	form = AuthenticationForm()
# 	return render(request=request, template_name="login/login.html", context={"form":form})

# def logout_request(request):
# 	logout(request)
# 	messages.info(request, "Você realizou logout com sucesso!") 
# 	return redirect("cars_urls:index")

# def register_request(request):
# 	if request.method == "POST":
# 		form = NewUserForm(request.POST)
# 		if form.is_valid():
# 			user = form.save()
# 			login(request, user)
# 			messages.success(request, "Registration successful." )
# 			return redirect("cars_urls:index")
# 		messages.error(request, "Unsuccessful registration. Invalid information.")	
# 	form = NewUserForm()
# 	return render (request=request, template_name="cadastros/register_form.html", context={"register_form":form})

users/templates/clientes/formClientes.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Cadastrar Aluguel
{% endblock %}

{% block centro %}
<div class="container p-4 col-xs-6 col-sm-4">

    <h1 class="text-center pt-4">Cadastro de Clientes</h1>
    <p class="lead text-center pt-4"> Preencha os campos abaixo:</p>

    <form action="." method="POST" class="p-4">

        {% csrf_token %}

        <div class="row ">

        {{ formCliente|crispy }}
            <div>
                <button type="submit" class="btn btn-primary mb-4 mt-4">Cadastrar</button>
            </div>
        </div>
    </form>

</div>
{% endblock %}

users/templates/clientes/formDelete.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block centro %}
<div class="container-fluid">

  <div class="main">
    <!-- Create a Form -->
    <form method="POST" class="p-4">
        <!-- Security token by Django -->
        {% csrf_token %}
        Tem certeza que quer deletar esse cliente?
        <input type="submit" class="btn btn-danger" value="Deletar"/>
        <button class="btn btn-secondary">
          <a href="{% url 'carros_urls:paginaInicial' %}" class="text-white"> 
            Cancelar
          </a>
        </button>
    </form>
  </div>

</div>
{% endblock %}

users/templates/clientes/listarClientes.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
Listar Locações
{% endblock %}

{% block centro %}
<div class="container-fluid p-4 text-center">

    <h1 class="text-align-center pb-4">Clientes Cadastrados</h1>

    <div class="row">

      {% for cliente in clientes %}

        <div class="col mb-5" >

          <div class="card" style="width: 18rem;">
            <div class="card-header">
              Cliente: {{ cliente.nome }}
              <a href="{% url 'usuarios_urls:deletarCliente' cliente.id %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>  
              </a>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">CPF: {{ cliente.cpf }}</li>
              <li class="list-group-item"> RG: {{ cliente.rg }} </li>
              <li class="list-group-item"> Telefone: {{ cliente.telefone }}</li>
              <li class="list-group-item">CNH: {{ cliente.numero_cnh }}</li>
              <li class="list-group-item">Endereço: {{ cliente.endereco }}</li>
            </ul>
          </div>
        
        </div>

      {% endfor %}
    
    </div>
    
</div>
{% endblock %}